### ISSUE TITLE
Searching for exclamation mark results in an error

### ISSUE THREAD

**Issue by chrschw** [Flowpack/Flowpack.SearchPlugin#39]
If you try to enter special characters like exclamation mark into the search request form you will get an error as result:

https://punkt.de/de/suche.html?search=now%21

( searched for: now! )

**Comment by kdambekalns** [comment]
Indeed. Well, `!` is one of the [reserved characters](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-query-string-query.html#_reserved_characters) in the query string syntax.

And `\!` does not work either, since it ends up as `\\\\!`, again leaving the exclamation mark unescaped.

**Comment by chrschw** [comment]
Yes and searching for: now"
also results in an error ...

**Comment by chrschw** [comment]
pull request for additional comments about this issue in the readme file created
