### ISSUE TITLE
v 4.1.0 breaks compatibility with Neos 4.x?

### ISSUE THREAD

**Issue by kdambekalns** [Flowpack/Flowpack.SearchPlugin#57]
A client of ours downgraded from 4.1.0 to 4.0.1 saying

> version 4.1.0 has Neos 5-only support and breaks the node indexing.

If that is the case,

- the composer manifest should no longer claim compatibility with Neos 4.x
- and/or it should have been a major release, not a minor one
- or compatibility should be restored with a 4.1.1

**Comment by kdambekalns** [comment]
@thelalaman Can you give some more details? That'd be great!

**Comment by daniellienert** [comment]
Just skimmed through the changes (https://github.com/Flowpack/Flowpack.SearchPlugin/compare/4.0.1...4.1.0), found nothing suspicious, that should not work with 4.0. 

Apart from that, if the issue is about indexing, the Search-Plugin should not be the cause ...

**Comment by markusguenther** [comment]
The issue comes from the mistakes in the neos/content-repository-search repository. The 3.0 was able to run with flow 5 until 3.0.7 and with the latest 3.0.8 it is not anymore. So, the people are not able to use PHP 7.4 for instance with Neos 4.3. 

https://github.com/neos/content-repository-search/issues/45

Guess we should also require 4.0 here to make it work again.
